export const CLOUD_TEMP_DIR_NAME = ".cloud";
export const RELEASE_CONFIGURATION_NAME = "release";

export const CRYPTO = {
	CERTIFICATE_HEADER: "-----BEGINCERTIFICATE-----",
	CERTIFICATE_FOOTER: "-----ENDCERTIFICATE-----",
	ORGANIZATION_FIELD_NAME: "O",
	COMMON_NAME_FIELD_NAME: "CN"
}

export const APPLE_INC = "Apple Inc.";